Feat/add categories page
OlhaDu/ACS_Beauty_Admin_new pull request #25
Opened 2024-01-08 13:16 UTC by KonstantinLigus

2024-01-09 06:48 UTC, rryaboshtan requested changes

2024-01-09 06:48 UTC, rryaboshtan commented on src/components/Toggler/Toggler.tsx
> +        {values.enabled ? <p>Увiмкнено</p> : <p>Вимкнено</p>}
лучше тег <p> поставить снаружи

2024-01-10 16:55 UTC, KonstantinLigus commented on src/components/AddCategory/AddCategory.module.scss
> +textarea.textArea {
тут нужно повысить приоритет селектора, чтоб перебить высоту для поля в `FormGenerator`

2024-01-10 20:22 UTC, KonstantinLigus commented on src/components/Category/Category.tsx
> +          <button onClick={arrowRightBtnClickHandler}>
onArrowRightBtnClick

2024-01-10 20:30 UTC, KonstantinLigus commented on src/pages/CategoriesPage/CategoriesPage.jsx
> +            activeCategory={activeCategory}
да, надо redux подключить

2024-01-11 09:07 UTC, KonstantinLigus commented on src/components/Border/Border.module.scss
> +.borderDefault {
смысл компонента `Border` в том, чтобы не передавать в него пропсом стили для `border` а передать пропс со строкой-названием стиля, и этот стиль (один из трех) применился согласно пропсу

2024-01-15 02:49 UTC, rryaboshtan requested changes

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/AddCategory/AddCategory.module.scss
> +textarea.textArea {
можно создать к примеру специальный класс стилей для этого

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/AddImageInput/AddImageInput.tsx
> +  }>();
да, но он не работает автоматически, нужно Ctrl+S нажимать в каждом файле

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/AddImageInput/AddImageInput.tsx
> +const AddImageInput = forwardRef((props, ref) => {
без forwardRef не работает??

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/AddCategory/AddCategory.module.scss
> +  @extend .Roboto500-20-23;
поменяй это на миксин с 3 пропсами

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/AddCategory/AddCategory.tsx
> +  const bgImgEl = useRef<{ clearBgImg: () => void }>(null)
можно использовать типизацию проще, что-то типа:
  const bgImgEl= useRef<HTMLDivElement>(null)

Не используй forwardRef и useImperativeHandle, оно работает и без этого, эти вещи только усложняют код

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/AddCategory/AddCategory.tsx
> +  const bgImgEl = useRef<{ clearBgImg: () => void }>(null)
просто image, у тебя сложное название переменной, в контексте категории image итак понятно что это означает

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/AddCategory/AddCategory.tsx
> +      const res = await api.addCategory(value)
здесь лучше использовать механизм try catch, тогда не нужно ставить if условие, потому что при неуспешной операции оно всё равно перекинет на catch, в catch к примеру можно пользователю на экран во всплывашке выводить, если есть 400-ые ошибки

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/Border/Border.tsx
> +  const borderClasses = classNames(s[border], className)
переименуй classNames на cn

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/FormGenerator/FormGenerator.tsx
> +  const { initialValues, validationSchema, groups, onSubmit, isToggler } = props
делай хотя бы где-то пустые строки кода, разделяй логические элементы кода пустой строкой, это сложно читать

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/FormGenerator/FormGenerator.tsx
> +                    {Component && <>{Component}</>}
просто {Component}

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/Toggler/Toggler.tsx
> +        className={`${s.toggle} ${values.enabled ? s.toggleActive : ""}`}
сделай через classNames

2024-01-15 02:49 UTC, rryaboshtan commented on src/components/VioletButton/VioletButton.tsx
> +    className={`${s.button} ${className}`}
используй classNames

2024-01-15 02:49 UTC, rryaboshtan commented on src/index.css
> +  font-family: inherit;
эта строка ничего не делает

2024-01-15 17:58 UTC, KonstantinLigus commented on src/index.css
> +  font-family: inherit;
без этой сторки    ` font-family: monospace;`

2024-01-15 20:22 UTC, rryaboshtan commented on src/components/AddImageInput/AddImageInput.tsx
> +const AddImageInput: FC<{ bgImageRef: null | RefObject<HTMLDivElement> }> = ({ bgImageRef }) => {
Просто:
interface Props {
  bgImageRef: null | RefObject<HTMLDivElement>
}
const AddImageInput: FC<Props> = ({ bgImageRef })

2024-01-15 20:23 UTC, rryaboshtan commented on src/components/FormGenerator/FormGenerator.tsx
> +                    <>{Component}</>
{Component} без угловых скобок

2024-01-15 20:36 UTC, rryaboshtan commented on src/index.css
> +  font-family: inherit;
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/4c809179-5279-4f06-8f85-a48a20c562f6)

Потому что здесь нужно не :root ставить а *

2024-01-15 20:42 UTC, rryaboshtan commented on src/index.css
> +  font-family: inherit;
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/dec3c021-3b82-4950-99d0-f132f80fdadc)

Закомменти пожалуйста это ужасное line-height 1.5

2024-01-15 20:42 UTC, rryaboshtan commented on src/index.css
> +  font-family: inherit;
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/064157c9-a5e4-4d63-b682-defa9e8e3ed5)

установи вот эту либу, она работает без конфликтов

2024-01-15 20:43 UTC, rryaboshtan commented on src/index.css
> +  font-family: inherit;
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/fe1895f5-b9c8-4027-bc5c-3bfe60673e2f)

и подключи в App.tsx

2024-01-17 10:25 UTC, KonstantinLigus commented on src/pages/CategoriesPage/CategoriesPage.jsx
> +            activeCategory={activeCategory}
поделючил редакс

2024-01-17 22:06 UTC, rryaboshtan requested changes

2024-01-18 16:15 UTC, KonstantinLigus commented on src/components/Categories/Categories.tsx
> +  }, [dispatch])
в принципе, єто не мешает особо

2024-01-18 16:15 UTC, KonstantinLigus commented on src/components/Categories/Categories.tsx
> +  }, [dispatch])
тогда придутся отключить проверку для єтого места

2024-01-18 16:19 UTC, merged