Feature/orders
OlhaDu/ACS_Beauty_Admin_new pull request #26
Opened 2024-01-09 11:04 UTC by iryna-zatynina

2024-01-11 19:38 UTC, rryaboshtan requested changes

2024-01-14 10:53 UTC, iryna-zatynina commented on src/components/Table/Table.tsx
> +    const columnsWithActions: GridColDef[] = hasActions
у меня да, но этот компонент может же быть переиспользован еще где-то

2024-01-18 17:16 UTC, iryna-zatynina commented on src/components/Table/Table.tsx
> +    onEdit?: (id: number) => void;
не описывала эти две функции в этом же компоненте так как этот копмонент используется на странице юзеров

2024-01-20 04:31 UTC, rryaboshtan requested changes

2024-01-20 04:31 UTC, rryaboshtan commented on src/components/Buttons/WhiteButton/WhiteButton.module.scss
> +  font-size: 16px;
лишняя строка

2024-01-20 04:31 UTC, rryaboshtan commented on src/components/Popups/ChangeOrderStatusPopup/ChangeOrderStatusPopup.tsx
> +                    <div className={s.radios__block}>
последующие блоки div можно описать выше в виде массива объектов и смапить сюда через array.map -> (<div></div>)

2024-01-20 04:31 UTC, rryaboshtan commented on src/components/Table/Table.tsx
> +    rows: OrdersRow[];
моки, которые ты ставишь в rows и columns лучше вынести в отдельную папку mocks, не держать их в файле React компонента, а здесь напрямую их подключить без пропсов

2024-01-20 04:31 UTC, rryaboshtan commented on src/components/Table/Table.tsx
> +const Table: React.FC<Props> = ({columns, rows, onEdit, onDelete}) => {
не используешь prettier

2024-01-20 04:31 UTC, rryaboshtan commented on src/components/ToolsPanel/ExportButton/ExportButton.tsx
> +interface Props {
то же самое, что и в предыдущем комментарии по rows и columns

2024-01-20 04:31 UTC, rryaboshtan commented on src/components/ToolsPanel/Select/Select.tsx
> +        <div className={styles.container} onClick={handleToggle} style={style}>
везде s вместо styles

2024-01-20 04:31 UTC, rryaboshtan commented on src/components/ToolsPanel/Select/Select.tsx
> +                style={!isOpen ? {borderTop: "none"} : {}}
style={isOpen ? {} : {borderTop: "none"}}

Пиши сначала положительное утверждение, потом отрицательное, так проще читать код

2024-01-20 04:31 UTC, rryaboshtan commented on src/index.css
>  :root {
здесь нужно поставить * вместо :root

2024-01-20 04:31 UTC, rryaboshtan commented on src/index.css
> +    line-height: 1.5;
убери эту строку, это слишком большое значение line-height

2024-01-20 04:31 UTC, rryaboshtan commented on src/pages/Orders/Orders.tsx
> +    const columns = [
моки закинь в отдельный файл mocks

2024-01-20 04:31 UTC, rryaboshtan commented on src/pages/Orders/Orders.tsx
> +    const [chosenOrderId, setChosenOrderId] = useState(null);
просто поставь 0, тогда TS автоматически подставит тип number и заказов с id 0 в базе не будет, т.е. это число можно использовать как отсутствие чего-либо и типизация будет в порядке, не нужно будет писать number | null

2024-01-20 04:31 UTC, rryaboshtan commented on src/pages/Orders/Orders.tsx
> +    const handleShowModal = (orderId: any) => {
orderId: number

2024-01-20 04:31 UTC, rryaboshtan commented on src/pages/Orders/Orders.tsx
> +        setChosenOrderId(null)
setChosenOrderId(0)

2024-01-20 04:31 UTC, rryaboshtan commented on src/pages/Orders/Orders.tsx
> +                    <Table
можно убрать пропсы rows и columns и подключить моки напрямую внутри компонента Table

2024-01-20 04:31 UTC, rryaboshtan commented on src/components/Table/Table.module.scss
>    height: 400;
используй 400px, по умолчанию оно считается не в пикселах, не используй значения вроде 70, 120, разве что 0 можно использовать

2024-01-24 16:05 UTC, merged