Feature/no ref/brands
OlhaDu/ACS_Beauty_Admin_new pull request #28
Opened 2024-01-13 20:31 UTC by UserAndrii

2024-01-13 22:52 UTC, rryaboshtan requested changes

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandsTableComponent/BrandsTableComponent.tsx
> +            "& .actions": {
& в этих трёх стилях не нужен

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandsTableComponent/BrandsTableComponent.tsx
> +            flexDirection: "column",
эта строка ничего не делает

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandsTableComponent/BrandsTableComponent.tsx
> +            width: "100%",
эти 2 строки ничего не делают, их можно убрать

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandManagementForm/BrandManagementForm.tsx
> +  brand?: IBrand | null | GridValidRowModel;
неправильная типизация, нужно вот так:
  brand?: IBrand;

тогда в компоненте BrandsTable нужно поменять:
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/af8037dd-dc51-4731-a6fc-db1a71e3c954)
вот так никаких проблем с типизацией не будет, и убираешь лишний код, у тебя метод find итак возвращает undefined, если ничего не нашёл

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandsTableComponent/BrandsTableComponent.tsx
> +interface IBrandsTableProps {
просто IProps, не нужно постоянно маячить, что это именно BrandsTable

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandsTableComponent/BrandsTableComponent.tsx
> +const BrandsTableComponent: React.FC<IBrandsTableProps> = ({
переименуй на BrandsTable, итак понятно, что это компонент по сигнатуре и по тому, что он находится в папке components, это дополнительное слово в имени не даёт никакой дополнительной информации, оно лишнее...

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandManagementForm/BrandManagementForm.tsx
> +const BrandManagementForm: React.FC<IBrandManagementFormProps> = ({
просто IProps

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandManagementForm/BrandManagementForm.tsx
> +  const [brandName, setBrandName] = useState<string>(brand?.name || "");
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/160f8a7b-d77e-4686-956d-5b0bbbcf9d72)
видишь, если убрать <string>, ts итак понимает что там строка по значению в круглых скобках

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandManagementForm/BrandManagementForm.tsx
> +  const [image, setImage] = useState<string | Blob>(brand?.logo || "");
здесь Blob вообще не нужен, нужно вот так:
const [image, setImage] = useState(brand?.logo || "");

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandManagementForm/BrandManagementForm.tsx
> +            src={typeof image === "string" ? image : ""}
здесь просто вот так: 
onClick={() => setImage("")}

2024-01-13 22:52 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandsTableComponent/columns.tsx
> +const formatDate = (dateString: string): string => {
вместо dateString лучше просто date

2024-01-13 22:52 UTC, rryaboshtan commented on src/pages/Brands/Brands.module.scss
> +  @extend .Roboto500-24-28;
замени миксином с тремя пропсами

2024-01-13 22:52 UTC, rryaboshtan commented on src/redux/brands/operations.tsx
> +interface BrandData {
просто Brand, не используй слова Data и Info в именах переменных и типов, они не дают никакой дополнительной информации

2024-01-16 09:12 UTC, UserAndrii commented on src/pages/Brands/Brands.tsx
> +  const [paginationModel, setPaginationModel] = useState<IPaginationModel>({
На жаль не можу зробити 2 state, тому що я мушу передавати саме обʼєкт в пропси DataGrid, де від динамічно розраховує і розбиває сторінки.

2024-01-20 03:21 UTC, rryaboshtan commented on src/pages/Brands/Brands.tsx
> +  const [paginationModel, setPaginationModel] = useState<IPaginationModel>({
ты бы мог 2 стэйта собрать уже в самом пропсе, к примеру вот так:
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/2c3be943-eda7-492d-8809-26dc10f810df)

2024-01-20 03:41 UTC, rryaboshtan requested changes

2024-01-20 03:41 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandManagementForm/BrandManagementForm.tsx
> +            className={`${s.brand_form__download_container} ${
используй либу classnames, оно будет выглядеть примерно вот так:
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/cc6b4d0d-6a6e-42ed-8d6b-68f358a5dcd0)

2024-01-20 03:41 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandManagementForm/BrandManagementForm.tsx
> +          className={`${s.brand_form__input} ${
classNames

2024-01-20 03:41 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandManagementForm/BrandManagementForm.tsx
> +          className={`${s.brand_form__textarea} ${
то же самое

2024-01-20 03:41 UTC, rryaboshtan commented on src/components/BrandsComponents/BrandsTable/BrandsTable.tsx
> +          paginationModel={paginationModel}
если бы ты их поставил в разные useState, ты мог бы прям в пропсе сформировать объект: 
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/f15c579a-907e-478b-bf1f-cfdab5a63413)

2024-01-20 03:41 UTC, rryaboshtan commented on src/components/ToolsPanel/SearchInput/SearchInput.tsx
> +    <div className={styles.searchInputContainer}>
s вместо styles

2024-01-20 03:41 UTC, rryaboshtan commented on src/components/ToolsPanel/SearchInput/SearchInput.tsx
> +        className={styles.searchInput}
s вместо styles

2024-01-20 03:41 UTC, rryaboshtan commented on src/components/ToolsPanel/SearchInput/SearchInput.tsx
> +      <SearchIcon className={styles.searchIcon} />
s вместо styles

2024-01-20 03:41 UTC, rryaboshtan commented on src/pages/Brands/Brands.tsx
> +  const [isOpenModal, setIsOpenModal] = useState<boolean>(false);
boolean можно не писать, хотя здесь это не принципиально

2024-01-22 18:30 UTC, merged