Redux/reviews
OlhaDu/ACS_Beauty_Admin_new pull request #50
Opened 2024-02-06 17:21 UTC by andrii-pozniak

2024-02-08 03:11 UTC, rryaboshtan requested changes

2024-02-08 03:11 UTC, rryaboshtan commented on src/hooks/useFilterOnClickOutside.tsx
> +const useFilterEffect = (
![image](https://github.com/OlhaDu/ACS_Beauty_Admin_new/assets/79945546/3c544ff6-4440-4e13-9389-0d7c2afbd894)
ещё есть такой вариант, также можно просто установить либу useOnClickOutside

2024-02-08 03:11 UTC, rryaboshtan commented on src/hooks/useFilterOnClickOutside.tsx
> +    const closeFilter = (e: MouseEvent) => {
этот хук можно вообще удалить, он у тебя уже есть

2024-02-08 03:11 UTC, rryaboshtan commented on src/images/svg/StarIcon.tsx
> +const StarIcon: FC<StarIconProps> = ({
просто Props

2024-02-08 03:11 UTC, rryaboshtan commented on src/pages/Reviews/Reviews.module.scss
> +  padding: 32px 20px 20px 20px;
можно 32px 20px 20px это то же самое

2024-02-08 03:11 UTC, rryaboshtan commented on src/pages/Reviews/Reviews.module.scss
> +  text-align: start;
удали эту строку

2024-02-08 03:11 UTC, rryaboshtan commented on src/pages/Reviews/Reviews.module.scss
> +  font-style: normal;
normal не имеет смысла

2024-02-08 03:11 UTC, rryaboshtan commented on src/pages/Reviews/Reviews.tsx
> +  }, [dispatch, searchName, pageSize, page, status, rating])
убери dispatch

2024-02-08 03:11 UTC, rryaboshtan commented on src/pages/Reviews/Reviews.tsx
> +            <ExportList />
Export button что-то типа такого должно быть

2024-02-08 03:11 UTC, rryaboshtan commented on src/redux/reviews/reviewsSlice.tsx
> +    ratingFilter: "positive" | "neutral" | "negative" | "all"
какой смысл этого вложенного поля, если ты можешь сделать просто переменную
На вот это "positive" | "neutral" | "negative" | "all" сделай отдельный тип данных в ts

2024-02-08 03:11 UTC, rryaboshtan commented on src/redux/reviews/reviewsSlice.tsx
> +function handlePending(state: { isLoading: boolean }) {
Эти 2 функции должны находиться в одном месте проекта, не в каждом слайсе
По идее их можно в папку utils выделить

2024-02-08 03:11 UTC, rryaboshtan commented on src/types/Reviews/IReview.ts
> +    review: string;
в этих двух строках должен быть конкретный тип, не просто строка

2024-02-08 03:11 UTC, rryaboshtan commented on vite.config.ts
> +    sourcemap: true,
source map наверно лучше true не ставить, чтобы нельзя было код проекта посмотреть на проде в devTools, хотя это нужно проверить...

2024-02-08 17:09 UTC, andrii-pozniak commented on src/api/reviews/instance.tsx
> +export const instance = axios.create({
исправил

2024-02-08 17:11 UTC, andrii-pozniak commented on src/components/Reviews/Modal/ChangeStatus.module.scss
> +  font-family: Roboto;
исправил

2024-02-08 17:11 UTC, andrii-pozniak commented on src/components/Reviews/Modal/ChangeStatus.module.scss
> +  font-size: 16px;
исправил

2024-02-08 17:14 UTC, andrii-pozniak commented on src/components/RowsOnPageFilter/RowsOnPageFilter.tsx
> +  const [isOpen, setIsOpen] = useState<boolean>(false)
это не мое

2024-02-08 17:14 UTC, andrii-pozniak commented on src/components/Utils/api/getReviews.js
> +  try {
удалил

2024-02-08 17:14 UTC, andrii-pozniak commented on src/components/Utils/api/getReviews.js
> +    const response = await axios.patch(`api/feedback/${id}`, credentials);
удалил

2024-02-08 17:18 UTC, andrii-pozniak commented on src/images/svg/StarIcon.tsx
> +const StarIcon: FC<StarIconProps> = ({
исправил

2024-02-08 17:20 UTC, andrii-pozniak commented on src/pages/Reviews/Reviews.module.scss
> +  padding: 32px 20px 20px 20px;
исправил

2024-02-08 17:20 UTC, andrii-pozniak commented on src/pages/Reviews/Reviews.module.scss
> +  text-align: start;
исправил

2024-02-08 17:20 UTC, andrii-pozniak commented on src/pages/Reviews/Reviews.module.scss
> +  font-style: normal;
исправил

2024-02-08 17:28 UTC, andrii-pozniak commented on src/redux/reviews/reviewsSlice.tsx
> +    ratingFilter: "positive" | "neutral" | "negative" | "all"
удалили

2024-02-08 17:35 UTC, andrii-pozniak commented on src/types/Reviews/IReview.ts
> +    review: string;
исправил

2024-02-08 18:50 UTC, andrii-pozniak commented on src/components/Reviews/FilterProperties/FilterProperties.module.scss
> +  @extend .Roboto400-16-18;
исправил

2024-02-08 18:51 UTC, andrii-pozniak commented on src/components/Reviews/FilterProperties/FilterProperties.module.scss
> +  text-align: "start";
исправил

2024-02-08 18:52 UTC, andrii-pozniak commented on src/components/Reviews/FilterProperties/FilterProperties.module.scss
> +  justify-content: end;
исправил

2024-02-10 10:10 UTC, andrii-pozniak commented on src/components/Reviews/FilterProperties/FilterProperties.tsx
> +                  <li>
исправил

2024-02-10 10:10 UTC, andrii-pozniak commented on src/components/Reviews/FilterProperties/FilterProperties.tsx
> +                  <li>
исправил

2024-02-10 10:18 UTC, andrii-pozniak commented on src/redux/reviews/reviewsSlice.tsx
> +function handlePending(state: { isLoading: boolean }) {
вынес в отдельную папку

2024-02-15 15:47 UTC, andrii-pozniak commented on src/components/Reviews/ExportList/ExportList.tsx
> +const ExportList = () => {
исправил

2024-02-18 18:27 UTC, rryaboshtan approved these changes

2024-02-18 18:27 UTC, rryaboshtan commented on src/components/Reviews/ReviewsItems/ReviewsTable.tsx
> +      <div className={s.statusStyle}>
Style думаю не нужно, итак очевидно что это стили, ты в className не можешь что-то другое описать

2024-02-20 17:21 UTC, closed without merging